name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rustfmt"
        run: rustup component add rustfmt

      - name: "rustfmt"
        run: cargo fmt --all --check

  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: "Tests"
        run: cargo nextest run

      - name: "Doctests"
        run: cargo test --doc
  
  integration:
    name: "integration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4

      - name: "Install Python"
        working-directory: example-dagster-pipes-rust-project
        run: uv python install

      - name: "Install the project"
        working-directory: example-dagster-pipes-rust-project
        run: uv sync --all-extras --dev

      - name: "Lint"
        working-directory: example-dagster-pipes-rust-project
        run: uv run make ruff 

      - name: "Tests"
        working-directory: example-dagster-pipes-rust-project
        run: uv run pytest example_dagster_pipes_rust_project_tests
