name: quality-check-dagster-teradata
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/dagster-teradata/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ./libraries/dagster-teradata
        run: uv python install 3.12

      - name: Sync dependencies
        working-directory: ./libraries/dagster-teradata
        run: uv sync --all-extras

      - name: Lint
        working-directory: ./libraries/dagster-teradata
        run: uv run ruff check

      - name: Check formatting
        working-directory: ./libraries/dagster-teradata
        run: uv run ruff format --check

      - name: Type check
        working-directory: ./libraries/dagster-teradata
        run: uv run pyright

      - name: Pytest
        working-directory: ./libraries/dagster-teradata
        run: uv run pytest --ignore=dagster_teradata_tests/functional/
